### ISSUE TITLE
Hello World Print hoy na

### ISSUE THREAD

**Issue by BDeshii** [24phyr/bup-bice-2022#1]
Vai hello world print hoy na. Help pls.

**Comment by T4H5iN** [comment]
vai https://24phyr.github.io/sauce.html e dhuke na. Fix it pls.

**Comment by 24phyr** [comment]
> Vai hello world print hoy na. Help pls.
Tell your papa for a GPU to render Hello World.


> vai https://24phyr.github.io/sauce.html e dhuke na. Fix it pls.
Issue fixed. Kindly check again.
